### ISSUE TITLE
Завдання для пр 5

### ISSUE THREAD

**Issue by Oleg4000** [Oleg4000/Oleg-1-Rozum-1#1]
Завдання: знайти магазини Arduino в львові

**Comment by Bronhit** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d144936.36387955022!2d30.378459379614647!3d50.423178033206526!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4c8e9bcca8b37%3A0xc4b1cb05a9a3508a!2zQXJkdWlubyDQo9C60YDQsNC40L3QsA!5e0!3m2!1suk!2sua!4v1479300657769" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

**Comment by Bronhit** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d144936.36387955022!2d30.378459379614647!3d50.423178033206526!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4c8e9bcca8b37%3A0xc4b1cb05a9a3508a!2zQXJkdWlubyDQo9C60YDQsNC40L3QsA!5e0!3m2!1suk!2sua!4v1479300657769" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

**Comment by Bronhit** [comment]
http://diylab.com.ua/g4923181-kontroleri-arduino
